name: CI
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.11"
      - uses: actions/checkout@v5
      - run: python -m pip install --upgrade black
      - run: black --check .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.11"
      - uses: actions/checkout@v5
      - run: python -m pip install flake8
      - run: flake8

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.11"
      - uses: actions/checkout@v5
      - run: python -m pip install psycopg isort==5.13.2
      - run: isort --diff --check .

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6.0.0
      - uses: actions/checkout@v5
      - run: python -m pip install -r docs/requirements.txt
      - run: cd docs/ && make html && make spelling

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", 3.11, 3.12, 3.13]
        django-version: [4.2, 5.1, 5.2, 6.0a1, "main"]
        postgres-version: ["postgres:14", "postgres:15", "postgres:16", "postgres:17", "postgres:18"]
        exclude:
            # Django 4.2
            - python-version: 3.13
              django-version: 4.2

            # Django 6.0
            - django-version: 6.0a1
              python-version: "3.10"
            - django-version: 6.0a1
              python-version: 3.11

            # Django main
            - django-version: main
              python-version: "3.10"
            - django-version: main
              python-version: 3.11
            - django-version: main
              postgres-version: "postgres:14"

    services:
      postgres:
        image: ${{ matrix.postgres-version }}
        env:
          POSTGRES_USER: modeltrans
          POSTGRES_PASSWORD: modeltrans
          POSTGRES_DB: modeltrans
        ports:
          - 5432:5432
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v5
      - run: python -m pip install Django==${{ matrix.django-version }}
        if: matrix.django-version != 'main'
      - run: python -m pip install https://github.com/django/django/archive/main.tar.gz
        if: matrix.django-version == 'main'
      - run: |
          python -m pip install coverage
          python -m pip install psycopg==3.1.12
      - run: coverage run --source=modeltrans manage.py test
